### ISSUE TITLE
Inventory file flag

### ISSUE THREAD

**Issue by faisalthaheem** [meltygroup/ansible-parallel#2]
Hello

Thank you for this useful package. 
A nice feature to have would be to specify which inventory file to be used, such as the case of when executing manually, for exmple
ansible-playbook -i myinventory playbooks/boo1.yaml

**Comment by JulienPalard** [comment]
Can you try:

     ansible-parallel playbooks/boo1.yaml -i myinventory

?

**Comment by faisalthaheem** [comment]
Thanks, that works.
